### ISSUE TITLE
Fails to load some COGs

### ISSUE THREAD

**Issue by giswqs** [mykolakozyr/cogviewer#1]
Very nice work! I was trying the streamlit app with some COGs from maxar, but it seems the app can't load the data. Any advice? Thanks. 

https://www.maxar.com/open-data/california-colorado-fires

https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif

https://opendata.digitalglobe.com/events/california-fire-2020/post-event/2020-08-14/pine-gulch-fire20/10300100AAC8DD00.tif

**Comment by mykolakozyr** [comment]
Thanks, @giswqs! And thanks for sharing links. 
I'll take a look, I had some issues with specific CORS settings on the bucket. It could be the case. When there is a tiler in between, as it is implemented in @vincentsarago [viewer](https://bl.ocks.org/vincentsarago/raw/e0608d470d9c5ba9d26359eebcc12ba2/#6.55/-34.537/150.184), then it's solved. 

The implementation of the current viewer does not have any tiler in between, so FE reads COG directly.

**Comment by robmarkcole** [comment]
I believe there is issue with single-band cogs (tracking on https://github.com/GeoTIFF/georaster-layer-for-leaflet/issues/16):
```
georaster-layer-for-leaflet:2 ERROR initializing GeoTIFFLayer pixelValuesToColorFn is a required option for single-band rasters
```

RE cors we resolved this by updating the bucket S3 CORS policy:
```json
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```

**Comment by mykolakozyr** [comment]
Hey @robmarkcole, thanks for sharing that! 
When I organize a bucket to share COGs, I do use those CORS settings as well. I believe in the case of the links shared by @giswqs, CORS settings are different.
The HTML page  that is added to Streamlit app as a component returns the following error when run locally:
`Access to fetch at 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

As a summary:
- This implementation of the viewer renders COG directly on a browser with no layer in between (like tiler). Therefore, this issue would happen once the bucket settings do not allow CORS.

I don't consider adding any tiler to the viewer at this moment based on the whole concept of COG, so considering closing the issue.
